# Generated by Django 4.2.1 on 2023-06-03 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_post_published_date_post_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='updated_date',
            new_name='published_date',
        ),
    ]
